version: '2'

services:

  aliabc-php-demo:
    hostname: aliabc-php-demo
    image: richarvey/nginx-php-fpm:latest
    entrypoint:
      - /bin/bash
    command: -c "cp -u /app/.env.example /app/.env; /start.sh"
    ports:
      - 80
    volumes:
      - .:/app
      - ./conf/nginx.conf:/etc/nginx/sites-available/default.conf